trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver
  - ast-v8-to-istanbul@1.0.2
  - '@angular-devkit/*'
  - '@angular/*'
  - '@schematics/angular@22.0.0'
  - 'ng-packagr@22.0.0'
minimumReleaseAgeExclude:
  - '@angular/*' # Exclude all packages under the @angular scope
  - '@schematics/angular' # Exclude the @schematics/angular package
  - '@angular-devkit/core'
  - '@angular-devkit/architect'
  - '@angular-devkit/schematics'
  - ng-packagr@22.0.0
  - '@angular-eslint/builder@22.0.0'
  - '@angular-eslint/bundled-angular-compiler@22.0.0'
  - '@angular-eslint/eslint-plugin-template@22.0.0'
  - '@angular-eslint/eslint-plugin@22.0.0'
  - '@angular-eslint/schematics@22.0.0'
  - '@angular-eslint/template-parser@22.0.0'
  - '@angular-eslint/utils@22.0.0'
  - angular-eslint@22.0.0
minimumReleaseAge: 2880 # Only install packages that are at least 2 days old
allowBuilds:
  '@parcel/watcher': false
  core-js: false
  esbuild: false
  lmdb: false
  msgpackr-extract: false
  sharp: false
nodeVersion: 26.1.0
engineStrict: true
resolutionmode: highest
