import { randomInt } from 'node:crypto';

export type CodeWordResponse = {
  code: string;
  length: number;
  alphabet: string;
  generatedAt: string;
};

const prefixes = [
  'amber',
  'amethyst',
  'apricot',
  'aqua',
  'aquamarine',
  'ash',
  'azure',
  'beige',
  'birch',
  'blue',
  'blueviolet',
  'brass',
  'bronze',
  'brown',
  'burgundy',
  'cadet',
  'carmine',
  'cerulean',
  'chartreuse',
  'cherry',
  'chocolate',
  'cobalt',
  'coffee',
  'coral',
  'cornflower',
  'cream',
  'crimson',
  'cyan',
  'dandelion',
  'denim',
  'emerald',
  'fuchsia',
  'gold',
  'goldenrod',
  'grape',
  'gray',
  'green',
  'honey',
  'ice',
  'indigo',
  'ivory',
  'jade',
  'jasmine',
  'juniper',
  'kelly',
  'lapis',
  'lavender',
  'lemon',
  'lime',
  'magenta',
  'mahogany',
  'maroon',
  'mauve',
  'mint',
  'mocha',
  'navy',
  'olive',
  'orange',
  'orchid',
  'peach',
  'pear',
  'periwinkle',
  'petal',
  'pink',
  'plum',
  'powder',
  'purple',
  'raspberry',
  'rose',
  'ruby',
  'saffron',
  'sage',
  'salmon',
  'sand',
  'scarlet',
  'sepia',
  'silver',
  'sky',
  'slate',
  'smoky',
  'teal',
  'thistle',
  'tomato',
  'turquoise',
  'ultramarine',
  'violet',
  'watermelon',
  'wheat',
  'wine',
  'yellow',
  'yellowgreen',
  'zinnia',
  'babyblue',
  'cinnamon',
  'copper',
  'limegreen',
  'sunset',
  'rust',
  'mintgreen',
  'peacock',
  'coralpink',
  'robinblue',
  'melon',
  'buttercup',
  'flax',
  'heather',
  'blush',
  'canary',
  'honeydew',
];

const infixes = [
  'albert',
  'atlas',
  'aurora',
  'avalanche',
  'baker',
  'basilisk',
  'beaver',
  'bison',
  'blizzard',
  'boomer',
  'brooklyn',
  'bulldozer',
  'camaro',
  'canary',
  'captain',
  'cardinal',
  'cargo',
  'cassidy',
  'centaur',
  'cheetah',
  'chorus',
  'cicada',
  'cobra',
  'comet',
  'condor',
  'corvette',
  'crimson',
  'cyclone',
  'dakota',
  'dolphin',
  'drifter',
  'eagle',
  'falcon',
  'ferrari',
  'firebird',
  'forest',
  'fox',
  'galaxy',
  'gazelle',
  'gemini',
  'glacier',
  'grizzly',
  'harbor',
  'hawk',
  'helix',
  'horizon',
  'hunter',
  'ibis',
  'impala',
  'indigo',
  'jaguar',
  'jet',
  'jupiter',
  'kangaroo',
  'kepler',
  'kitten',
  'komodo',
  'lancer',
  'lemur',
  'lion',
  'lotus',
  'lynx',
  'magellan',
  'marmot',
  'mercury',
  'meteor',
  'mirage',
  'monarch',
  'mongoose',
  'mustang',
  'nebula',
  'ninja',
  'nova',
  'otter',
  'owl',
  'pacific',
  'panda',
  'parrot',
  'pebble',
  'pelican',
  'phantom',
  'phoenix',
  'pilot',
  'pioneer',
  'porcupine',
  'quasar',
  'rabbit',
  'raven',
  'rocket',
  'rover',
  'sailor',
  'sapphire',
  'saturn',
  'scooter',
  'seahawk',
  'sentinel',
  'shadow',
  'shark',
  'sierra',
  'skylark',
  'snowfox',
  'solstice',
  'sparrow',
  'spirit',
  'sunset',
  'swan',
  'talon',
  'tango',
  'tiger',
  'timber',
  'tomahawk',
  'torpedo',
  'trailblazer',
  'tundra',
  'turbo',
  'vanguard',
  'velvet',
  'venture',
  'viper',
  'voyager',
  'walrus',
  'wasp',
  'whistler',
  'wildcat',
  'willow',
  'windsor',
  'yankee',
  'yellowstone',
  'zephyr',
  'zenith',
  'zebra',
  'polaris',
  'hazel',
  'vector',
  'vortex',
  'cobalt',
  'harrier',
  'mariner',
  'sprinter',
  'puma',
  'dragon',
  'orion',
];

const suffixes = [
  'apron',
  'backpack',
  'belt',
  'beret',
  'blazer',
  'boots',
  'bow',
  'bracelet',
  'cape',
  'cardigan',
  'cloak',
  'coat',
  'cowl',
  'dress',
  'earmuffs',
  'frock',
  'gloves',
  'gown',
  'hat',
  'hoodie',
  'hood',
  'jacket',
  'jeans',
  'jumpsuit',
  'kimono',
  'kilt',
  'leggings',
  'mittens',
  'overalls',
  'parka',
  'pajamas',
  'polo',
  'poncho',
  'robe',
  'sash',
  'scarf',
  'shawl',
  'shirt',
  'shoes',
  'skirt',
  'socks',
  'suit',
  'sweater',
  'sweatshirt',
  'tanktop',
  'tee',
  'tie',
  'tights',
  'trousers',
  'tunic',
  'umbrella',
  'underlayer',
  'vest',
  'waistcoat',
  'wallet',
  'watch',
  'windbreaker',
  'yarn',
  'accessory',
  'anklet',
  'bag',
  'bandana',
  'beanie',
  'bikini',
  'breeches',
  'brogues',
  'buttondown',
  'cap',
  'chaps',
  'coatdress',
  'crocs',
  'culottes',
  'duffel',
  'earrings',
  'fleece',
  'flipflops',
  'gaiters',
  'garter',
  'glasses',
  'goggles',
  'handbag',
  'headband',
  'headset',
  'heels',
  'jodhpurs',
  'kneehighs',
  'knitwear',
  'largewallet',
  'loafers',
  'longcoat',
  'moccasins',
  'muffler',
  'necktie',
  'overcoat',
  'peacoat',
  'pocketwatch',
  'pullover',
  'raincoat',
  'sandals',
  'suspenders',
  'sweatpants',
  'thermals',
  'trenchcoat',
  'turtleneck',
  'utilitybelt',
  'visor',
  'waistbelt',
  'woolcoat',
  'workshirt',
  'workwear',
  'zipjacket',
  'alpinehat',
  'fedora',
  'buckethat',
  'sunhat',
  'baseballcap',
  'beaniehat',
  'woolhat',
  'cowboyhat',
  'pithhelmet',
  'stormhat',
  'hoodedcoat',
  'wintercoat',
];

export const codeWordPermutations = prefixes.length * infixes.length * suffixes.length;
export const uniqueCodeWordPermutations = prefixes.length * new Set(infixes).size * suffixes.length;

export const codeWordCaseVariantCount =
  prefixes.reduce((sum, prefix) => sum + 2 ** prefix.length, 0) *
  infixes.reduce((sum, infix) => sum + 2 ** infix.length, 0) *
  suffixes.reduce((sum, suffix) => sum + 2 ** suffix.length, 0) -
  codeWordPermutations;

export const effectiveCodeWordPermutations = codeWordCaseVariantCount;

export function generateCodeWord(): CodeWordResponse {
  const prefix = prefixes[randomInt(prefixes.length)];
  const infix = infixes[randomInt(infixes.length)];
  const suffix = suffixes[randomInt(suffixes.length)];
  const baseCode = `${prefix}-${infix}-${suffix}`;

  // Randomly uppercase between 1 and all uppercasable characters (excluding hyphens)
  // to maximize entropy in generated codes.
  function randomizeCase(s: string): string {
    const chars = s.split('');
    const eligibleIndices = chars
      .map((ch, i) => ({ ch, i }))
      .filter(x => x.ch !== '-')
      .map(x => x.i);

    if (eligibleIndices.length === 0) return s;

    // pickCount in 1..eligibleIndices.length (max entropy)
    const pickCount = randomInt(eligibleIndices.length + 1);
    const picks = new Set<number>();
    while (picks.size < pickCount) {
      const pick = eligibleIndices[randomInt(eligibleIndices.length)];
      picks.add(pick);
    }

    for (const idx of picks) {
      chars[idx] = chars[idx].toUpperCase();
    }

    return chars.join('');
  }

  const code = randomizeCase(baseCode);

  return {
    code,
    length: code.length,
    alphabet: 'mixed-case high-entropy words with hyphen separators',
    generatedAt: new Date().toISOString(),
  };
}
