services:
  app:
    build:
      context: .
    container_name: random-code-microservice
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
