name: buildArtifacts
description: Compiles and caches all code into the dist folder
inputs:
  node-version:
    description: The node version to use for the module.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: get nodeModules from cache
      uses: ./.github/module-cache
      with:
        node-version: ${{ inputs.node-version }}
    - name: cache build artifacts
      id: cache-dist
      uses: actions/cache@v4
      with:
        path: dist
        # I only want to cache the dist folder for this workflow run
        key: dist-${{ inputs.node-version }}-${{ github.run_id }}

    # Set up GitHub Actions caching for Wireit.
    - uses: google/wireit@setup-github-actions-caching/v2

    - name: Build the dist artifacts, when not yet cached for this workflow
      if: steps.cache-dist.outputs.cache-hit != 'true'
      run: |
        npm run build.deploy
        cp dist/samples/browser/index.csr.html dist/samples/browser/index.html
        cp dist/samples/browser/index.html dist/samples/browser/404.html
      shell: bash
