name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [26.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Setup pnpm
        uses: pnpm/action-setup@v6.0.8
        with:
          version: 11
          cache: true
      - name: Setup Node, install dependencies, and cache node modules, build dist artifacts
        uses: ./.github/build-artifacts
        with:
          node-version: ${{ matrix.node }}
      - name: Upload dist artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # for future expansion, currently only one node version is configured
        node: [26.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3
      - name: Download dist artifact
        uses: actions/download-artifact@v8.0.1
        with:
          name: dist
          path: dist
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/samples/browser # The folder the action should deploy.
